version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-jwt-app
    ports:
      - "8501:8501"
    env_file:
      - .env
      - .jwt.env
    environment:
      STREAMLIT_SERVER_PORT: 8501
    # mount your config json & .env instead of baking them into the image
    volumes:
      - ./config.json:/app/config.json:ro
      - ./.env:/app/.env:ro
      - ./.jwt.env:/app/.jwt.env:ro
      - ./assets:/app/assets:ro
